FROM golang:alpine as builder

RUN apk update && apk add git && apk add ca-certificates

RUN adduser -D -g '' appuser 

COPY am $GOPATH/src/github.com/linkai-io/am/
COPY database $GOPATH/src/github.com/linkai-io/database
WORKDIR $GOPATH/src/github.com/linkai-io/database

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags '-w -s' -o /go/bin/pgm cmd/pgm/main.go

# STEP 2 build a small image
# start from scratch
FROM scratch
# Copy our static executable and supporting
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /go/bin/pgm /go/bin/pgm 
COPY --from=builder $GOPATH/src/github.com/linkai-io/database/pg_migrations /tmp/migrations
USER appuser 

ENTRYPOINT ["/go/bin/pgm", "-dir", "/tmp/migrations", "up"]